projects:
  awsserverlessairline:
    schemaPath: src/graphql/schema.json
    includes:
      - src/frontend/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/frontend/graphql
