projects:
  awsserverlessairline:
    schemaPath: amplify/backend/api/awsserverlessairline/build/schema.graphql
    includes:
      - src/frontend/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/frontend/graphql
extensions:
  amplify:
    version: 3
