version: '3.2'

# run Cypress tests and exit with command
#   docker-compose up --exit-code-from ui
services:
  # Cypress container
  ui:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e
    command: cypress run --project ./ui/
