/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:7846a3f4-7cd8-4b3f-985c-783f41449764",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_kONh3kbvS",
    "aws_user_pools_web_client_id": "ru41pbg2npionhjeem6f7gjf8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yewlfjbyl5bg3gcz2iep4xmcou.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
