AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Environment stage or git branch

  FlightTable:
    Type: String
    Description: Flight Table

Resources:
  ReserveFlight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: reserve.lambda_handler
      Runtime: python3.7
      CodeUri: src/reserve-flight
      Timeout: 10
      Environment:
        Variables:
          FLIGHT_TABLE_NAME: !Ref FlightTable

  ReleaseFlight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: release.lambda_handler
      Runtime: python3.7
      CodeUri: src/release-flight
      Timeout: 10
      Environment:
        Variables:
          FLIGHT_TABLE_NAME: !Ref FlightTable

  ReserveFlightParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Stage}/service/catalog/reserveFunction
      Description: Reserve Flight Lambda ARN
      Type: String
      Value: !Sub ${ReserveFlight.Arn}

  ReleaseFlightParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Stage}/service/catalog/releaseFunction
      Description: Release Flight Lambda ARN
      Type: String
      Value: !Sub ${ReleaseFlight.Arn}

Outputs:
  ReserveFlightFunction:
    Value: !Sub ${ReserveFlight.Arn}
    Description: Collect Payment Lambda Function

  ReleaseFlightFunction:
    Value: !Sub ${ReserveFlight.Arn}
    Description: Collect Payment Lambda Function
